import { createHash } from "node:crypto";
import { createReadStream, promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { z } from "zod";
import { formatBytes, mb, pct } from "./format.js";
import { ScanJob, findNode, isWithin, type DirNode } from "./scanner.js";
import { audit, runPowerShell } from "./ops.js";
import { fail, noScanMessage, ok, registry, resolveInput, type ToolDef, type ToolResult } from "./shared.js";

const IS_WIN = process.platform === "win32";

function pickJob(p?: string): { job: ScanJob; abs: string } | ToolResult {
  if (p) {
    const abs = resolveInput(p);
    const job = registry.findDone(abs);
    return job ? { job, abs } : noScanMessage(abs);
  }
  const job = registry.latestDone();
  return job ? { job, abs: job.root } : fail("No finished scan yet. Call scan_folder first.");
}

const isResult = (v: unknown): v is ToolResult => typeof v === "object" && v !== null && "content" in v;

interface FolderHit {
  path: string;
  node: DirNode;
}

/** Find folders by name anywhere below `basePath`. Matches are not searched further. */
function searchFolders(base: DirNode, basePath: string, matches: (name: string) => boolean): FolderHit[] {
  const hits: FolderHit[] = [];
  const walk = (node: DirNode, nodePath: string) => {
    for (const c of node.children) {
      const cp = path.join(nodePath, c.name);
      if (matches(c.name)) hits.push({ path: cp, node: c });
      else walk(c, cp);
    }
  };
  walk(base, basePath);
  return hits;
}

function nameMatcher(patterns: string[]): (name: string) => boolean {
  const regs = patterns.map((p) => new RegExp("^" + p.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*").replace(/\?/g, ".") + "$", "i"));
  return (name) => regs.some((r) => r.test(name));
}

async function withModified(hits: FolderHit[], olderThanDays?: number) {
  const now = Date.now();
  const rows = await Promise.all(
    hits.map(async (h) => {
      let mtime: number | undefined;
      try {
        mtime = (await fs.lstat(h.path)).mtimeMs;
      } catch {
        // Folder vanished since the scan.
      }
      return { ...h, mtime, days: mtime ? Math.floor((now - mtime) / 86400000) : undefined };
    })
  );
  return olderThanDays != null ? rows.filter((r) => r.days != null && r.days >= olderThanDays) : rows;
}

const DEV_ARTIFACTS: Record<string, string> = {
  node_modules: "npm install, yarn or pnpm install",
  ".venv": "recreate the virtual environment and reinstall",
  venv: "recreate the virtual environment and reinstall",
  __pycache__: "regenerated automatically",
  ".pytest_cache": "regenerated automatically",
  ".mypy_cache": "regenerated automatically",
  ".ruff_cache": "regenerated automatically",
  ".tox": "regenerated by tox",
  ".next": "rebuild the project",
  ".nuxt": "rebuild the project",
  ".svelte-kit": "rebuild the project",
  ".parcel-cache": "rebuild the project",
  ".turbo": "regenerated automatically",
  ".angular": "regenerated automatically",
  ".gradle": "rebuilt by Gradle",
  Pods: "pod install",
  DerivedData: "rebuilt by Xcode",
  ".dart_tool": "flutter pub get",
};

async function hashFile(file: string, bytes?: number): Promise<string> {
  const hash = createHash("sha1");
  const stream = createReadStream(file, bytes ? { start: 0, end: bytes - 1 } : undefined);
  for await (const chunk of stream) hash.update(chunk as Buffer);
  return hash.digest("hex");
}

async function mapLimit<T, R>(items: T[], limit: number, deadline: number, fn: (i: T) => Promise<R>): Promise<Array<R | undefined>> {
  const out: Array<R | undefined> = new Array(items.length);
  let next = 0;
  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, async () => {
      while (next < items.length && Date.now() < deadline) {
        const i = next++;
        try {
          out[i] = await fn(items[i]);
        } catch {
          out[i] = undefined;
        }
      }
    })
  );
  return out;
}

// ---- snapshots

const SNAPSHOT_DEPTH = 4;
const SNAPSHOT_MIN_BYTES = mb(10);

function snapshotDir(): string {
  return path.join(os.homedir(), ".diskscout", "snapshots");
}

function collectFolders(root: DirNode): Map<string, number> {
  const out = new Map<string, number>();
  const walk = (node: DirNode, rel: string, depth: number) => {
    for (const c of node.children) {
      if (c.size < SNAPSHOT_MIN_BYTES) continue;
      const r = rel ? rel + path.sep + c.name : c.name;
      out.set(IS_WIN ? r.toLowerCase() : r, c.size);
      if (depth < SNAPSHOT_DEPTH) walk(c, r, depth + 1);
    }
  };
  walk(root, "", 1);
  return out;
}

interface Snapshot {
  name: string;
  root: string;
  createdAt: string;
  totalBytes: number;
  files: number;
  folders: Array<[string, number]>;
}

const safeName = (s: string) => s.replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80) || "snapshot";

const PS_BIN_INFO = `
$s = (New-Object -ComObject Shell.Application).NameSpace(0xA)
$items = @($s.Items())
$sum = [int64]0
foreach ($i in $items) { $sum += [int64]$i.Size }
"{0},{1}" -f $items.Count, $sum
`;

async function recycleBinInfo(): Promise<{ items: number; bytes: number }> {
  const out = await runPowerShell(PS_BIN_INFO, {}, 90000);
  const [items, bytes] = out.split(",").map(Number);
  if (!Number.isFinite(items) || !Number.isFinite(bytes)) throw new Error(`Unexpected output: ${out.slice(0, 100)}`);
  return { items, bytes };
}

export const extraTools: ToolDef[] = [
  {
    name: "find_dev_artifacts",
    title: "Find developer build folders",
    description:
      "Find folders that projects can rebuild: node_modules, Python virtual environments and caches, Gradle, Next.js and similar build caches. Shows size, how long since each was touched and how to restore it. Needs a finished scan. Read only. To remove one, use move_to_recycle_bin.",
    inputSchema: {
      path: z.string().optional().describe("Limit to this folder. Defaults to the most recent scan."),
      min_size_mb: z.number().min(0).default(50).describe("Hide folders smaller than this many MB."),
      older_than_days: z.number().min(0).optional().describe("Only folders not modified for at least this many days."),
      limit: z.number().int().min(1).max(200).default(40).describe("Maximum rows to return."),
    },
    readOnly: true,
    destructive: false,
    handler: async ({ path: p, min_size_mb, older_than_days, limit }) => {
      const picked = pickJob(p);
      if (isResult(picked)) return picked;
      const base = findNode(picked.job, picked.abs);
      if (!base) return fail(`${picked.abs} was not found in the scan of ${picked.job.root}.`);
      const lookup = new Map(Object.entries(DEV_ARTIFACTS).map(([k, v]) => [k.toLowerCase(), v]));
      const hits = searchFolders(base, picked.abs, (n) => lookup.has(n.toLowerCase())).filter((h) => h.node.size >= mb(min_size_mb));
      const rows = (await withModified(hits, older_than_days)).sort((a, b) => b.node.size - a.node.size);
      const shown = rows.slice(0, limit).map((r) => ({ path: r.path, size_bytes: r.node.size, size: formatBytes(r.node.size), days_since_modified: r.days, restore_with: lookup.get(path.basename(r.path).toLowerCase()) }));
      const total = rows.reduce((s, r) => s + r.node.size, 0);
      const text = shown.length
        ? shown.map((d) => `${d.size.padStart(9)}  ${String(d.days_since_modified ?? "?").padStart(4)}d  ${d.path}`).join("\n") + `\nTotal rebuildable: ${formatBytes(total)} in ${rows.length} folder(s).`
        : "No matching folders.";
      return ok(text, { folders: shown, total_bytes: total, total: formatBytes(total), matches: rows.length });
    },
  },
  {
    name: "find_folders",
    title: "Find folders by name",
    description: "Find folders by name anywhere in a scanned path, with sizes. Names are case insensitive and may use * and ? wildcards, for example [\"cache*\", \"temp\"]. Needs a finished scan. Read only.",
    inputSchema: {
      names: z.array(z.string()).min(1).max(20).describe("Folder names or patterns to look for."),
      path: z.string().optional().describe("Limit to this folder. Defaults to the most recent scan."),
      min_size_mb: z.number().min(0).default(0).describe("Hide folders smaller than this many MB."),
      older_than_days: z.number().min(0).optional().describe("Only folders not modified for at least this many days."),
      limit: z.number().int().min(1).max(200).default(30).describe("Maximum rows to return."),
    },
    readOnly: true,
    destructive: false,
    handler: async ({ names, path: p, min_size_mb, older_than_days, limit }) => {
      const picked = pickJob(p);
      if (isResult(picked)) return picked;
      const base = findNode(picked.job, picked.abs);
      if (!base) return fail(`${picked.abs} was not found in the scan of ${picked.job.root}.`);
      const hits = searchFolders(base, picked.abs, nameMatcher(names)).filter((h) => h.node.size >= mb(min_size_mb));
      const rows = (await withModified(hits, older_than_days)).sort((a, b) => b.node.size - a.node.size).slice(0, limit);
      const data = rows.map((r) => ({ path: r.path, size_bytes: r.node.size, size: formatBytes(r.node.size), files: r.node.files, days_since_modified: r.days }));
      const text = data.length ? data.map((d) => `${d.size.padStart(9)}  ${String(d.days_since_modified ?? "?").padStart(4)}d  ${d.path}`).join("\n") : "No matching folders.";
      return ok(text, { folders: data });
    },
  },
  {
    name: "find_duplicates",
    title: "Find duplicate files",
    description:
      "Find identical large files among the biggest files of a scan. Files are grouped by size, then compared by content hash, so this reads file contents. Needs a finished scan. Stops after about 40 seconds and says so. Read only. Review the groups before removing any copy.",
    inputSchema: {
      path: z.string().optional().describe("Limit to this folder. Defaults to the most recent scan."),
      min_size_mb: z.number().min(0).default(10).describe("Ignore files smaller than this many MB."),
      limit: z.number().int().min(1).max(100).default(20).describe("Maximum duplicate groups to return."),
    },
    readOnly: true,
    destructive: false,
    handler: async ({ path: p, min_size_mb, limit }) => {
      const picked = pickJob(p);
      if (isResult(picked)) return picked;
      const deadline = Date.now() + 40000;
      const minBytes = mb(min_size_mb);
      const bySize = new Map<number, string[]>();
      for (const f of picked.job.topFiles) {
        if (f.size < minBytes || f.size === 0 || !isWithin(picked.abs, f.path)) continue;
        const list = bySize.get(f.size);
        if (list) list.push(f.path);
        else bySize.set(f.size, [f.path]);
      }
      const sameSize = [...bySize.entries()].filter(([, files]) => files.length > 1);
      const groups: Array<{ size: number; files: string[] }> = [];
      let incomplete = false;

      for (const [size, files] of sameSize) {
        if (Date.now() >= deadline) {
          incomplete = true;
          break;
        }
        const quick = await mapLimit(files, 4, deadline, (f) => hashFile(f, 1024 * 1024));
        const byQuick = new Map<string, string[]>();
        files.forEach((f, i) => {
          const h = quick[i];
          if (!h) return;
          byQuick.set(h, [...(byQuick.get(h) ?? []), f]);
        });
        for (const candidates of byQuick.values()) {
          if (candidates.length < 2) continue;
          const full = await mapLimit(candidates, 4, deadline, (f) => hashFile(f));
          const byFull = new Map<string, string[]>();
          candidates.forEach((f, i) => {
            const h = full[i];
            if (!h) {
              incomplete = true;
              return;
            }
            byFull.set(h, [...(byFull.get(h) ?? []), f]);
          });
          for (const same of byFull.values()) if (same.length > 1) groups.push({ size, files: same });
        }
      }

      groups.sort((a, b) => b.size * (b.files.length - 1) - a.size * (a.files.length - 1));
      const data = groups.slice(0, limit).map((g) => ({ size_bytes: g.size, size: formatBytes(g.size), copies: g.files.length, wasted_bytes: g.size * (g.files.length - 1), wasted: formatBytes(g.size * (g.files.length - 1)), files: g.files }));
      const wastedTotal = groups.reduce((s, g) => s + g.size * (g.files.length - 1), 0);
      const text = data.length
        ? data.map((d) => `${d.wasted.padStart(9)} wasted  ${d.copies} copies of ${d.size}\n${d.files.map((f) => "           " + f).join("\n")}`).join("\n") + `\nTotal wasted by duplicates: ${formatBytes(wastedTotal)}.`
        : "No duplicates found among the largest files.";
      return ok(text + (incomplete ? "\nStopped early, results are incomplete. Narrow the path or raise min_size_mb." : ""), { groups: data, wasted_total_bytes: wastedTotal, incomplete });
    },
  },
  {
    name: "save_snapshot",
    title: "Save a snapshot",
    description:
      "Save the folder sizes of a finished scan to disk so a later scan can be compared against it. Keeps folders of 10 MB or more, four levels deep. Stored in ~/.diskscout/snapshots. Writes one small file, never touches your data.",
    inputSchema: {
      path: z.string().optional().describe("Scanned folder to snapshot. Defaults to the most recent scan."),
      name: z.string().optional().describe("Name for the snapshot. Defaults to the folder and the date."),
    },
    readOnly: false,
    destructive: false,
    handler: async ({ path: p, name }) => {
      const picked = pickJob(p);
      if (isResult(picked)) return picked;
      const node = findNode(picked.job, picked.abs);
      if (!node) return fail(`${picked.abs} was not found in the scan.`);
      const stamp = new Date().toISOString().slice(0, 16).replace(/[:T]/g, "-");
      const finalName = safeName(name ?? `${picked.abs}-${stamp}`);
      const folders = [...collectFolders(node).entries()].sort((a, b) => b[1] - a[1]).slice(0, 20000);
      const snap: Snapshot = { name: finalName, root: picked.abs, createdAt: new Date().toISOString(), totalBytes: node.size, files: node.files, folders };
      await fs.mkdir(snapshotDir(), { recursive: true });
      const file = path.join(snapshotDir(), `${finalName}.json`);
      await fs.writeFile(file, JSON.stringify(snap));
      await audit({ action: "save_snapshot", name: finalName, root: picked.abs });
      return ok(`Saved snapshot "${finalName}" of ${picked.abs}: ${formatBytes(node.size)}, ${folders.length} folders recorded. Scan again later and run compare_snapshot to see what changed.`, { name: finalName, file, folders: folders.length, total_bytes: node.size });
    },
  },
  {
    name: "compare_snapshot",
    title: "Compare against a snapshot",
    description:
      "Show which folders grew or shrank since a saved snapshot. Needs a fresh finished scan that covers the snapshot's folder. Call without a name to list saved snapshots. Read only.",
    inputSchema: {
      name: z.string().optional().describe("Snapshot name. Leave out to list snapshots."),
      min_change_mb: z.number().min(0).default(50).describe("Hide changes smaller than this many MB."),
      limit: z.number().int().min(1).max(100).default(20).describe("Maximum rows per direction."),
    },
    readOnly: true,
    destructive: false,
    handler: async ({ name, min_change_mb, limit }) => {
      let files: string[] = [];
      try {
        files = (await fs.readdir(snapshotDir())).filter((f) => f.endsWith(".json"));
      } catch {
        // No snapshots yet.
      }
      if (!name) {
        const list = await Promise.all(
          files.map(async (f) => {
            const s = JSON.parse(await fs.readFile(path.join(snapshotDir(), f), "utf8")) as Snapshot;
            return { name: s.name, root: s.root, created: s.createdAt, total: formatBytes(s.totalBytes) };
          })
        );
        return ok(list.length ? list.map((l) => `${l.name}  ${l.root}  ${l.total}  ${l.created.slice(0, 16)}`).join("\n") : "No snapshots saved yet. Use save_snapshot after a scan.", { snapshots: list });
      }
      const file = path.join(snapshotDir(), `${safeName(name)}.json`);
      let snap: Snapshot;
      try {
        snap = JSON.parse(await fs.readFile(file, "utf8")) as Snapshot;
      } catch {
        return fail(`No snapshot named "${name}". Call compare_snapshot without a name to list them.`);
      }
      const job = registry.findDone(snap.root);
      if (!job) return fail(`Scan ${snap.root} first so there is something to compare. Use scan_folder with rescan true for fresh numbers.`);
      const node = findNode(job, snap.root);
      if (!node) return fail(`${snap.root} was not found in the current scan.`);
      const before = new Map(snap.folders);
      const after = collectFolders(node);
      const minBytes = mb(min_change_mb);
      const rows: Array<{ rel: string; before: number; after: number; delta: number }> = [];
      for (const rel of new Set([...before.keys(), ...after.keys()])) {
        const b = before.get(rel) ?? 0;
        const a = after.get(rel) ?? 0;
        if (Math.abs(a - b) >= minBytes) rows.push({ rel, before: b, after: a, delta: a - b });
      }
      const fmt = (r: (typeof rows)[number]) => ({ path: path.join(snap.root, r.rel), before: formatBytes(r.before), after: formatBytes(r.after), change: (r.delta >= 0 ? "+" : "-") + formatBytes(Math.abs(r.delta)), delta_bytes: r.delta });
      const grew = rows.filter((r) => r.delta > 0).sort((a, b) => b.delta - a.delta).slice(0, limit).map(fmt);
      const shrank = rows.filter((r) => r.delta < 0).sort((a, b) => a.delta - b.delta).slice(0, limit).map(fmt);
      const totalDelta = node.size - snap.totalBytes;
      const line = (d: ReturnType<typeof fmt>) => `${d.change.padStart(10)}  ${d.before} to ${d.after}  ${d.path}`;
      const text = `${snap.root} since ${snap.createdAt.slice(0, 16)}: ${formatBytes(snap.totalBytes)} to ${formatBytes(node.size)} (${totalDelta >= 0 ? "+" : "-"}${formatBytes(Math.abs(totalDelta))}).\nGrew:\n${grew.map(line).join("\n") || "  nothing"}\nShrank:\n${shrank.map(line).join("\n") || "  nothing"}`;
      return ok(text, { total_change_bytes: totalDelta, grew, shrank, percent_change: pct(totalDelta, snap.totalBytes) });
    },
  },
  {
    name: "recycle_bin_info",
    title: "Recycle Bin size",
    description: "Show how many items are in the Windows Recycle Bin and roughly how much space they use. Windows only. Read only.",
    inputSchema: {},
    readOnly: true,
    destructive: false,
    handler: async () => {
      if (!IS_WIN) return fail("The Recycle Bin tools are Windows only.");
      const info = await recycleBinInfo();
      return ok(`Recycle Bin: ${info.items} item(s), about ${formatBytes(info.bytes)}.`, { items: info.items, bytes: info.bytes, size: formatBytes(info.bytes) });
    },
  },
  {
    name: "empty_recycle_bin",
    title: "Empty the Recycle Bin",
    description:
      "Permanently empty the Windows Recycle Bin on all drives. Items cannot be recovered afterwards. Windows only. Defaults to a dry run that only reports what is in it. Set dry_run to false only after the user agreed.",
    inputSchema: {
      dry_run: z.boolean().default(true).describe("When true nothing is deleted."),
    },
    readOnly: false,
    destructive: true,
    handler: async ({ dry_run }) => {
      if (!IS_WIN) return fail("The Recycle Bin tools are Windows only.");
      const before = await recycleBinInfo();
      if (dry_run) return ok(`Dry run. The Recycle Bin holds ${before.items} item(s), about ${formatBytes(before.bytes)}. Nothing was deleted. Run again with dry_run false to empty it.`, { dry_run: true, items: before.items, bytes: before.bytes });
      if (before.items === 0) return ok("The Recycle Bin is already empty.", { dry_run: false, items: 0, bytes: 0 });
      await runPowerShell("Clear-RecycleBin -Force -ErrorAction Stop", {}, 10 * 60 * 1000);
      await audit({ action: "empty_recycle_bin", items: before.items, bytes: before.bytes });
      return ok(`Emptied the Recycle Bin: ${before.items} item(s), about ${formatBytes(before.bytes)} freed.`, { dry_run: false, items: before.items, bytes: before.bytes, freed: formatBytes(before.bytes) });
    },
  },
  {
    name: "scan_status",
    title: "Scan status",
    description: "List the scans held in memory with their progress, speed and age. Optionally cancel a running scan. Read only apart from cancelling.",
    inputSchema: {
      cancel_path: z.string().optional().describe("Root path of a running scan to cancel."),
    },
    readOnly: true,
    destructive: false,
    handler: async ({ cancel_path }) => {
      let cancelled = "";
      if (cancel_path) {
        const abs = resolveInput(cancel_path);
        const running = registry.list().find((j) => j.status === "running" && j.root.toLowerCase() === abs.toLowerCase());
        if (!running) return fail(`No running scan for ${abs}.`);
        running.cancel();
        cancelled = `Cancelled the scan of ${running.root}.\n`;
      }
      const jobs = registry.list().map((j) => ({
        scan_id: j.id,
        root: j.root,
        status: j.status,
        engine: j.engineUsed,
        files: j.filesSeen,
        size: formatBytes(j.bytesSeen),
        seconds: Math.round(j.durationMs / 100) / 10,
        files_per_second: j.filesPerSecond,
        age_minutes: Math.round((Date.now() - (j.finishedAt ?? Date.now())) / 60000),
      }));
      const text = jobs.length ? jobs.map((j) => `${j.status.padEnd(9)} ${j.root}  ${j.files.toLocaleString()} files, ${j.size}, ${j.seconds}s, ${j.files_per_second.toLocaleString()}/s (${j.engine})`).join("\n") : "No scans in memory.";
      return ok(cancelled + text, { scans: jobs });
    },
  },
];
